[SETTINGS]
edited = 
owner = Default
path = C:\Users\...\Developer-Assistant\test-project
changelog = C:\Users\...\Developer-Assistant\test-project\CHANGELOG.md
version = 1.0.0
command = git add CHANGELOG.md
;; the command could be anything, DA will run it in your project folder if you add it (runs in "Format & commit")
cloud = 